#!/usr/bin/env python3
import json,re,urllib.request
from pathlib import Path
ORCID="0000-0001-6526-7740"
HEAD={"Accept":"application/json","User-Agent":"JorgeRodasAcademicSite/5.0 (mailto:jrodass@unemi.edu.ec)"}
def get(url):
 req=urllib.request.Request(url,headers=HEAD)
 with urllib.request.urlopen(req,timeout=45) as r:return json.load(r)
def doi(ids):
 for x in ids or []:
  if str(x.get("external-id-type","")).lower()=="doi":
   return re.sub(r"^https?://(dx\.)?doi\.org/","",x.get("external-id-value",""),flags=re.I)
 return ""
def main():
 raw=get(f"https://pub.orcid.org/v3.0/{ORCID}/works")
 rows=[]
 for g in raw.get("group",[]):
  s=(g.get("work-summary") or [{}])[0]
  title=(((s.get("title") or {}).get("title") or {}).get("value") or "Untitled work").strip()
  year=(((s.get("publication-date") or {}).get("year") or {}).get("value") or "—")
  journal=(s.get("journal-title") or {}).get("value") or ""
  d=doi((s.get("external-ids") or {}).get("external-id") or [])
  url=f"https://doi.org/{d}" if d else ((s.get("url") or {}).get("value") or f"https://orcid.org/{ORCID}")
  rows.append({"year":str(year),"title":title,"journal":journal,"doi":d,"url":url,"type":str(s.get("type") or "Publication").replace("_"," ").title(),"authors":"Jorge Rodas-Silva et al.","open_access":False})
 seen=set(); out=[]
 for p in sorted(rows,key=lambda x:(x["year"],x["title"]),reverse=True):
  key=("doi:"+p["doi"].lower()) if p["doi"] else ("title:"+re.sub(r"\W+","",p["title"].lower()))
  if key not in seen:seen.add(key);out.append(p)
 Path("data/publications.json").write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding="utf-8")
 metrics=json.loads(Path("data/metrics.json").read_text(encoding="utf-8"))
 metrics["publications"]=len(out)
 metrics["recent_visible"]=min(4,len(out))
 metrics["journals"]=sum("journal" in p["type"].lower() for p in out)
 metrics["conference_papers"]=sum("conference" in p["type"].lower() for p in out)
 metrics["book_chapters"]=sum("book" in p["type"].lower() for p in out)
 metrics["doi_links"]=sum(bool(p["doi"]) for p in out)
 Path("data/metrics.json").write_text(json.dumps(metrics,ensure_ascii=False,indent=2),encoding="utf-8")
 # The page renderer is generated by rebuild_site.py.
 import rebuild_site
 rebuild_site.rebuild(out,metrics)
if __name__=="__main__":main()
